### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#10]
![uploads/cbf1bf96-9510-401c-abb2-2ca69d58249b/terms_conditions.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcbf1bf96-9510-401c-abb2-2ca69d58249b%2Fterms_conditions.png)

**Comment by aprilfx** [comment]
Need to add Chinese version https://www.basf.com/cn/zh/tools/legal/disclaimer.html

**Comment by matthewmayer** [comment]
added zh
