### ISSUE TITLE
Innovation Area: Subsection

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#12]

**Comment by matthewmayer** [comment]
@asundgren please assign to me once design signed off

**Comment by asundgren** [comment]
Sketch: https://www.dropbox.com/s/9ssgyxo6hhr2o7v/BASF%20UI%20v02.sketch?dl=0
- [ ] update image for Innovation article 3, Let your City Shine
![innovation article 3](https://user-images.githubusercontent.com/6083880/38971650-ad678884-43ce-11e8-96c7-417584bb5e31.png)

- [ ] update image for Innovation article 2, Let your Journey Shine
![innovation article 2](https://user-images.githubusercontent.com/6083880/38971651-ad9f0f84-43ce-11e8-8303-b8e457f5f7e1.png): 

- [ ] update image for Innovation article 1, Let your Day Shine
![innovation article 1](https://user-images.githubusercontent.com/6083880/38971648-ad2f0770-43ce-11e8-8474-71ee91da6b0d.png)
