### ISSUE TITLE
Activity Schedule: Fashion Show

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#15]
![uploads/bdddc1f3-5b13-4ce9-a76e-4fb6928abef8/activity_fashion_show.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbdddc1f3-5b13-4ce9-a76e-4fb6928abef8%2Factivity_fashion_show.png)

**Comment by matthewmayer** [comment]
Will show most recent 4 items.

**Comment by aprilfx** [comment]
![img_6635](https://user-images.githubusercontent.com/2369167/38297663-c6b70704-3827-11e8-86da-61162ed7d098.PNG)

It doesn't show any image here?
