### ISSUE TITLE
Catwalk Chemistry: BTS Mini Doc

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#19]
![uploads/0802895b-ea49-4aca-bab2-ef08dbf49905/catwalk_chemistry_bts_mini_doc_01.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0802895b-ea49-4aca-bab2-ef08dbf49905%2Fcatwalk_chemistry_bts_mini_doc_01.png)

**portrait video**

![uploads/838a5b93-506d-4c88-9631-729bf737f3c6/catwalk_chemistry_video_portrait.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F838a5b93-506d-4c88-9631-729bf737f3c6%2Fcatwalk_chemistry_video_portrait.png)

**landscape video**

![uploads/3d86aa60-1c0c-4de3-9b5b-9908f03be4dd/catwalk_chemistry_video_landscape.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3d86aa60-1c0c-4de3-9b5b-9908f03be4dd%2Fcatwalk_chemistry_video_landscape.png)

**Comment by aprilfx** [comment]
![wechatimg165](https://user-images.githubusercontent.com/2369167/38294606-f79d7dee-381d-11e8-961d-b918276858d4.jpeg)

**Comment by asundgren** [comment]
- [ ] remove the view materials for this section
