### ISSUE TITLE
Bug: Personal information form is not showing correctly

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#25]
Backend
![wechatimg574](https://user-images.githubusercontent.com/2369167/37755724-9a4fdc2c-2de1-11e8-904b-a29a99eb31b6.jpeg)

Frontend
![wechatimg573](https://user-images.githubusercontent.com/2369167/37755740-a699508a-2de1-11e8-8cb5-265a97955fb2.jpeg)

**Comment by matthewmayer** [comment]
Fixed, note you don't have to enter answers for the "Personal Information Form" question type, they appear automatically.
