### ISSUE TITLE
Bug: Set format requirement for the personal information page of survey

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#26]
![img_6349](https://user-images.githubusercontent.com/2369167/37820028-5d8dde54-2eba-11e8-91a9-d8d24546c1b9.PNG)

Now you can type anything in the fields, like pop up number keyboard when adding phone number, also need alert for the wrong format like: 
That's not a correct email, please type the correct email address

**Comment by matthewmayer** [comment]
added email and phone attributes

**Comment by aprilfx** [comment]
if you input "abc" as email

Expect: it show alert that email is not correct
Actual: it goes to the thank you page
