### ISSUE TITLE
Bug: home page become smaller when hit send code button

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#27]
![img_6345](https://user-images.githubusercontent.com/2369167/37820163-c9c2d692-2eba-11e8-958f-9314ef3ec4d9.PNG)

1. Type name and phone number
2. Tap send code button

Expect: the home page will not become smaller
Actual: it became smaller

**Comment by aprilfx** [comment]
![img_6409](https://user-images.githubusercontent.com/2369167/37945294-163d5d90-31b2-11e8-8779-07267b05bf53.PNG)

The background color changed, but the image still doesn't fit the screen

**Comment by matthewmayer** [comment]
already noted in #6
