### ISSUE TITLE
Bug: need better Chinese translation for all pages and placeholders

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#30]

**Comment by matthewmayer** [comment]
@aprilfx @JamesZST  you can directly edit https://github.com/reigndesign/basfchinaplas/blob/master/app/i18n/zh.json for this 

Note you will need to let me know when edited so I can deploy.

**Comment by aprilfx** [comment]
done the changes, please deploy

**Comment by matthewmayer** [comment]
@aprilfx  deployed

**Comment by aprilfx** [comment]
@matt please deploy again

**Comment by matthewmayer** [comment]
@aprilfx redeployed

**Comment by aprilfx** [comment]
updated with copy from client, please deploy
