### ISSUE TITLE
Catwalk chemistry upload

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#35]
1. Brand rep goes to secret page http://basfchinaplas2018.com/upload/f9r662syrfvfddq8

2. Drag & drop images and videos into 1 of the three dropzones

3. Images will be resized to 640 pixels across. Videos will not be resized. Maximum upload size is 50 megabytes

4. Images and videos will appear on the Media page on the dashboard most recent first
http://basfchinaplas2018.com/dashboard/photos

5. Images and videos will also appear on the sub pages of the chemistry catwalk section

http://basfchinaplas2018.com/en/chemistry/fashion
http://basfchinaplas2018.com/en/chemistry/booth
http://basfchinaplas2018.com/en/chemistry/documentary

Note these pages are not fully styled yet, see #20 and #19

**Comment by aprilfx** [comment]
![img_6426](https://user-images.githubusercontent.com/2369167/37959907-d145d106-31e6-11e8-996b-72f8ceea7fcc.PNG)

- [ ] it doesn't show the most recent uploaded first, the second one was not uploaded by me just now

![img_6425](https://user-images.githubusercontent.com/2369167/37960011-0ccb645c-31e7-11e8-9dd7-11eeb074f511.PNG)

- [ ] each time opening the page, it doesn't show video preview unless you play the video

![img_6424](https://user-images.githubusercontent.com/2369167/37960054-2a8ddbb4-31e7-11e8-8390-be4ce29d4ef0.PNG)

- [ ] the vertical images are uploaded as horizental

**Comment by aprilfx** [comment]
It still doesn't show the video

**Comment by matthewmayer** [comment]
@aprilfx unfortunately i think thats just a browser limitation. Some browsers automatically display a thumbnail (e.g. Chrome desktop) and some don't (e.g. Mobile Safari).

**Comment by aprilfx** [comment]
Can we try the fake thumbnail like canon does here? It links to safari and somehow shows the thumbnail there
http://m.canon.com.cn/specialsite/photogirls/mobile/special/cp/cp6.html

**Comment by aprilfx** [comment]
and this expensive look cosmetic page works, too http://www.laprairie.com.cn/cn/essence-in-lotion/95790-01205-40.html?utm_source=KOL&utm_medium=KOL&utm_campaign=SC-EIL&utm_content=SLPBG
the play button looks like Youku though...

**Comment by matthewmayer** [comment]
We can do it for static videos like the mini documentary but we cannot do it for dynamically uploaded videos like the fashion show because that would require generation of thumbnail automatically for each video which I think is out of scope

**Comment by aprilfx** [comment]
Well I think the client won't be happy with it...will do some searching on how to solve this tmr...

**Comment by aprilfx** [comment]
![image 4](https://user-images.githubusercontent.com/2369167/38085859-c4fb81b2-3384-11e8-8556-9bdfc3717880.png)

Can we try changing the preload from "metadata" to "auto"? It seems will preload everything of the video, but immediately showed the thumbnail in safari

**Comment by matthewmayer** [comment]
changed preload
