### ISSUE TITLE
Bug: need more consistent alert and translation

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#39]
![img_6403](https://user-images.githubusercontent.com/2369167/37945158-62dc7010-31b1-11e8-8a66-7c75ed9d6208.PNG)
请输入姓名
![img_6404](https://user-images.githubusercontent.com/2369167/37945159-633d33be-31b1-11e8-8838-ed6379270116.PNG)
验证码错误，请重试
![img_6405](https://user-images.githubusercontent.com/2369167/37945160-638921ac-31b1-11e8-9771-66c5c1db64fc.PNG)
请输入您要提问的内容

**Comment by matthewmayer** [comment]
It's not consistent because required fields use the browser validation, which will use your device language, but errors will use custom validation, which we can translate and style.
