### ISSUE TITLE
Bug: Survey - type in the content will dismiss the selection

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#40]
1. Select "other" in the survey
2. Tap the typing are to type something
3. Observe
Expect: The option "other" will stay selected
Actual: The option "other" is not selected

**Comment by matthewmayer** [comment]
cannot reproduce. which browser?

**Comment by aprilfx** [comment]
in wechat and in safari, I guess it is because if you try to type, it will auto-select the option, if I select the option and try to type content, it will auto-unselect the option
![2018-03-28 12_13_04](https://user-images.githubusercontent.com/2369167/38008466-6756f61c-3281-11e8-8c0d-b647b344a5f5.gif)

**Comment by aprilfx** [comment]
you are right, android works fine
