### ISSUE TITLE
Register: International phone number support

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#5]
![uploads/0b607171-8c19-4234-b462-aa7cb7cc3675/register_2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0b607171-8c19-4234-b462-aa7cb7cc3675%2Fregister_2.png)

![uploads/b5b87664-39ca-43c1-9ca1-5952667ec7fc/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb5b87664-39ca-43c1-9ca1-5952667ec7fc%2Fimage.png)

![uploads/fcef30b5-853b-4c3e-816a-97daf55fb074/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffcef30b5-853b-4c3e-816a-97daf55fb074%2Fimage.png)

**Comment by matthewmayer** [comment]
Please test functionality first for international SMS. If working OK then can finish styling. 

I used https://www.proovl.com/test for testing receiving SMS. If you sign up for a free account you can test receiving some SMS for some foreign numbers.

**Comment by aprilfx** [comment]
![img_6595](https://user-images.githubusercontent.com/2369167/38224746-fa0a04f8-3723-11e8-83e1-9a809d1dc4dd.PNG)
Need to align the content from country code picker

**Comment by matthewmayer** [comment]
i think current solution is OK for now. not a major feature.
