### ISSUE TITLE
Bug: change QR code links

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#52]
1. Open the page in wechat
2. Select English
3. Log in
4. Close the page
5. Reopen the page in wechat
6. Observe

Expect: it should show English version
Actual: it goes back to Chinese version

**Comment by matthewmayer** [comment]
@aprilfx What URL are you opening at 1

**Comment by aprilfx** [comment]
I think it is the url we sent for QR code, all of them have "zh" 
- 1. Main (landing page/main menu) - http://basfchinaplas2018.com/zh
- 2. Interactive floor plan - http://basfchinaplas2018.com/zh/map
- 3.  Transportation article - http://basfchinaplas2018.com/zh/map/1
- 4. Lifestyle article - http://basfchinaplas2018.com/zh/map/3
- 5. Infrastructure article - http://basfchinaplas2018.com/zh/map/4
- 6. Customer enquiry - http://basfchinaplas2018.com/zh/contact
- 7. Survey - http://basfchinaplas2018.com/zh/survey

**Comment by matthewmayer** [comment]
that is expected behaviour then

**Comment by matthewmayer** [comment]
Language redirection now works.

Additionally, if you go to a QR code url when not logged in, it will redirect to register page but it will remember which page you were trying to access, and then it will redirect to that page after you log in.
