### ISSUE TITLE
Update hamburger button to a house shape button

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#53]

**Comment by asundgren** [comment]
Menu icon updated to home icon as attached.
Sketch: https://www.dropbox.com/s/9ssgyxo6hhr2o7v/BASF%20UI%20v02.sketch?dl=0
![survey 1](https://user-images.githubusercontent.com/6083880/38609712-bd9ec2b4-3db9-11e8-96d2-b3f137ede4fd.png)

![activity schedule 1 copy](https://user-images.githubusercontent.com/6083880/38609709-bcdae57e-3db9-11e8-81a7-0852389f5c8a.png)
![catwalk chemistry 1](https://user-images.githubusercontent.com/6083880/38609710-bd1575cc-3db9-11e8-9583-0b7e29a1e0c7.png)
![innovation area 1 copy](https://user-images.githubusercontent.com/6083880/38609711-bd60ad30-3db9-11e8-9280-9047cfce90e8.png)

**Comment by aprilfx** [comment]
![img_6807](https://user-images.githubusercontent.com/2369167/38713208-9f831380-3f02-11e8-9a10-5b96913e6ff0.PNG)

Need to move the house button left so the margin stays the same with the back button on the left
