### ISSUE TITLE
Fix layout in data protection page

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#54]
![img_6721](https://user-images.githubusercontent.com/2369167/38495429-1f261d96-3c2c-11e8-9826-b11b3cb9dc5f.JPG)

**Comment by asundgren** [comment]
Sketch: https://www.dropbox.com/s/9ssgyxo6hhr2o7v/BASF%20UI%20v02.sketch?dl=0

![data protection](https://user-images.githubusercontent.com/6083880/38611211-0a7de926-3dbe-11e8-9e2b-df8dbf2352e5.png)

**Comment by matthewmayer** [comment]
fixed - it's not identical to the design but as this is a boring page i think doesnt matter too much
