### ISSUE TITLE
Contact page connections

### ISSUE THREAD

**Issue by JamesZST** [reigndesign/basfchinaplas#59]
http://basfchinaplas2018.com/zh/contact

in this page, when user click the submission button, it shall be able to sends an email to chinaplas@basf.com and store the info into our backend. @matthewmayer

**Comment by matthewmayer** [comment]
now sends emails to chinaplas@basf.com and stores in backend at http://basfchinaplas2018.com/dashboard/contacts

**Comment by matthewmayer** [comment]
i just tested it. according to sendwithus the email was sent.


![uploads/061ebc3d-fce2-4400-9ab6-d84f652967c3/Screenshot 2018-04-18 20.14.52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F061ebc3d-fce2-4400-9ab6-d84f652967c3%2FScreenshot+2018-04-18+20.14.52.png)

**Comment by aprilfx** [comment]
okay, let's see if client confirm they received

**Comment by JamesZST** [comment]
They have checked also in their junk mailbox, still not received the email. The email sender is SendGrid?

**Comment by matthewmayer** [comment]
Yes. Maybe their corporate firewall is blocking it? I would suggest they just use the dashboard to export all the contacts at the end of the event instead.

**Comment by matthewmayer** [comment]
Or they could set up a separate account for example at Gmail or QQ to receive the emails

**Comment by aprilfx** [comment]
Okay let's ask Jonny about that, we will have a call in 2 mins
