### ISSUE TITLE
Register 1

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#6]
![uploads/b5c9b56f-dad5-4780-8f43-432623c6d9f0/register_one.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb5c9b56f-dad5-4780-8f43-432623c6d9f0%2Fregister_one.png)

**Comment by matthewmayer** [comment]
Note top section should fit to screen. Scroll down to go to register2 (#7)

**Comment by aprilfx** [comment]
![img_6378](https://user-images.githubusercontent.com/2369167/37888796-d24311b8-30fb-11e8-8308-a16315f72982.PNG)

the top section doesn't fit the screen

**Comment by asundgren** [comment]
- [ ] should be able to tap on the arrow to transition/auto-scroll to next step
- [ ] key visual should fill the screen width of the screen
- [ ] title should anchor 56px below the brand bar

**Comment by valentinard** [comment]
Please check the changes.

**Comment by asundgren** [comment]
Looks good
