### ISSUE TITLE
Innovation areas view: need to align the text content left and right (justify text)

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#62]
![img_6792](https://user-images.githubusercontent.com/2369167/38655572-10a53fae-3e48-11e8-9ca3-fd77bf156e48.PNG)
![img_6793](https://user-images.githubusercontent.com/2369167/38655573-10e19dc8-3e48-11e8-92c0-b77dfc315f98.PNG)
![img_6794](https://user-images.githubusercontent.com/2369167/38655574-11186150-3e48-11e8-946b-42a7eb55bd09.PNG)
![img_6795](https://user-images.githubusercontent.com/2369167/38655575-1152d24a-3e48-11e8-9559-fbea2352437e.PNG)
![img_6796](https://user-images.githubusercontent.com/2369167/38655576-118f4356-3e48-11e8-9884-24e49fde23d2.PNG)

**Comment by matthewmayer** [comment]
removed justify
