### ISSUE TITLE
Tech talk change

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#64]
![img_6878](https://user-images.githubusercontent.com/2369167/38789775-1bfd22e8-416f-11e8-8fc1-3210d7c03b0a.PNG)

Need to have a separate "Topic" line
Because the client want to see "Tech talk" on the top, but no "Tech talk" in "Topic" line

**Comment by matthewmayer** [comment]
now there is a separate field in the backend for this.
