### ISSUE TITLE
Dash + App: Add multiple speakers to Activity schedule view and Tech talk details view

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#66]
Design needed

**Comment by matthewmayer** [comment]
You can now edit what the Speaker: title is for specific sessions. @aprilfx please edit as needed.


![uploads/3f523ae4-0354-467c-a349-df556bb88db0/Screenshot 2018-04-17 08.52.36.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3f523ae4-0354-467c-a349-df556bb88db0%2FScreenshot+2018-04-17+08.52.36.png)

![uploads/7ba80c65-7a0a-4a12-9999-24a1a157f149/Screenshot 2018-04-17 08.52.31.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7ba80c65-7a0a-4a12-9999-24a1a157f149%2FScreenshot+2018-04-17+08.52.31.png)
