### ISSUE TITLE
Fashion show photos: add overlay and copy

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#70]
Enable the text overlay for each image. Copy to be provided by Freeman
with grey overlay in the bottom similar to wechat moments:
![img_6888](https://user-images.githubusercontent.com/2369167/38803195-09d38a9e-41a1-11e8-8775-b83e0c93ee6d.PNG)

Need to be able to add the copy from the dashboard

**Comment by matthewmayer** [comment]
@aprilfx do we need separate captions for english and chinese?

i think this should probably be a two-step process

1. Upload using http://basfchinaplas2018.com/upload/f9r662syrfvfddq8
2. Go to http://basfchinaplas2018.com/dashboard/photos and add captions
