### ISSUE TITLE
Dashboard: add gift code/phone number input area and a redeem button

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#73]
- The clients wants to input the gift code/phone number to redeem gift for users
- Once you type the gift code/phone number, it will match with the user list, to see if the user has redeemed the gift, the redeemed ones will be marked as redeemed
- If the user hasn't redeem gift, the redeem button will be clickable
- If the user has redeemed gift, the redeem button will be greyed out and show alert saying "redeemed"

**Comment by matthewmayer** [comment]
http://basfchinaplas2018.com/dashboard/redemptions

**Comment by aprilfx** [comment]
The user should be able to redeem the gift with either gift code or phone number

**Comment by aprilfx** [comment]
Sorry, let's remove the phone number, because phone number can't prove the user has completed the survey

**Comment by matthewmayer** [comment]
now only asks for the code

**Comment by aprilfx** [comment]
cool thanks!
