### ISSUE TITLE
Add new QR codes that can adapt device language

### ISSUE THREAD

**Issue by aprilfx** [reigndesign/basfchinaplas#81]
Andreas has generate the QR codes for:

3Gun 
http://basfchinaplas2018.com/qr/sessions/5a9fe533c7718e00041302c2/qa

CFMOTO
http://basfchinaplas2018.com/qr/sessions/5a9fe5f5c7718e00041302c3/qa

Ultrason
http://basfchinaplas2018.com/qr/sessions/5a9fe720c7718e00041302c5/qa

Plascobot
http://basfchinaplas2018.com/qr/sessions/5a9fe784c7718e00041302c6/qa

Sports Flooring
http://basfchinaplas2018.com/qr/sessions/5acdc8a868673e37b63c5237/qa

Ultramid
http://basfchinaplas2018.com/qr/sessions/5a9fed17c7718e00041302d2/qa

**Comment by matthewmayer** [comment]
This already works. I dont think any changes are needed to the site.

**Comment by aprilfx** [comment]
Weird, if I scan the qr code with my device in Chinese, it shows English page

**Comment by matthewmayer** [comment]
It defaults to the language you registered with
