### ISSUE TITLE
Cant access site after scanning individual QR codes for Q&A

### ISSUE THREAD

**Issue by asundgren** [reigndesign/basfchinaplas#83]
When you scan and enter the Q&A page there's no way to go back to the page unless you post a question. 

3Gun 
http://basfchinaplas2018.com/qr/sessions/5a9fe533c7718e00041302c2/qa

CFMOTO
http://basfchinaplas2018.com/qr/sessions/5a9fe5f5c7718e00041302c3/qa

Ultrason
http://basfchinaplas2018.com/qr/sessions/5a9fe720c7718e00041302c5/qa

Plascobot
http://basfchinaplas2018.com/qr/sessions/5a9fe784c7718e00041302c6/qa

Sports Flooring
http://basfchinaplas2018.com/qr/sessions/5acdc8a868673e37b63c5237/qa

Ultramid
http://basfchinaplas2018.com/qr/sessions/5a9fed17c7718e00041302d2/qa

**Comment by matthewmayer** [comment]
fixed close button
