### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by matthewmayer** [reigndesign/basfchinaplas#9]
![uploads/782120c9-b6c0-471e-a9d1-3c4220b95ccb/privacy_policy.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F782120c9-b6c0-471e-a9d1-3c4220b95ccb%2Fprivacy_policy.png)

**Comment by aprilfx** [comment]
Need Chinese versionhttps://www.basf.com/cn/zh/tools/legal/data-protection.html

**Comment by matthewmayer** [comment]
added zh
